version: '3.8'
services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nest-boiler
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    networks:
      - nest-boiler
    volumes:
      - nest-boiler:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s

networks:
  nest-boiler:
    driver: bridge

volumes:
  nest-boiler:
    driver: local