version: '3.8'
services:
  nestjs:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    networks:
      - nest_boiler
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - nest_boiler
    volumes:
      - nest_boiler:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7.4.0
    networks:
      - nest_boiler
    volumes:
      - nest_boiler:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  nest_boiler:
    driver: bridge

volumes:
  nest_boiler:
    driver: local
